// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJobrT8szvACtnUGO1K7RXHWdzuk_Nc9s',
    appId: '1:306956430654:web:a012dba4fa3740e4f7506f',
    messagingSenderId: '306956430654',
    projectId: 'financas-1b0ee',
    authDomain: 'financas-1b0ee.firebaseapp.com',
    storageBucket: 'financas-1b0ee.appspot.com',
    measurementId: 'G-VHLV5HV5M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IOwNAO3KhHmI-JxJMFStbxgi2HiNduc',
    appId: '1:306956430654:android:c2fc096a74540caef7506f',
    messagingSenderId: '306956430654',
    projectId: 'financas-1b0ee',
    storageBucket: 'financas-1b0ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8rvy-o9ZQ-0oBW-vbFjNRxAW26VjDKpc',
    appId: '1:306956430654:ios:4ee523998a96091df7506f',
    messagingSenderId: '306956430654',
    projectId: 'financas-1b0ee',
    storageBucket: 'financas-1b0ee.appspot.com',
    iosBundleId: 'com.example.financas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8rvy-o9ZQ-0oBW-vbFjNRxAW26VjDKpc',
    appId: '1:306956430654:ios:b785a7e8165c1e90f7506f',
    messagingSenderId: '306956430654',
    projectId: 'financas-1b0ee',
    storageBucket: 'financas-1b0ee.appspot.com',
    iosBundleId: 'com.example.financas.RunnerTests',
  );
}
